url: "http://localhost:4000"
baseurl: /portfolio/

# Site settings
title: Mahdieh Nejati
email: m.nejati@u.northwestern.edu
description: "Just a place to document my robotics work."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
# So that I am centered :)
- name: Mahdieh Nejati
  pic: mahdieh-small
  position: Roboticist
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/mahdiehnejati
    - title: github
      url: https://github.com/MahdiehNejati
    - title: stack-overflow
      url: 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/smileymahdieh
  - title: linkedin
    url: https://www.linkedin.com/in/mahdiehnejati
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: https://bitbucket.org/dashboard/overview
  - title: github
    url: https://github.com/MahdiehNejati

# Postal address (add as many lines as necessary)
address:
  - line: Chicago, IL
  #- line: 

# Build settings
markdown: kramdown
permalink: pretty